// ============================================================
// 基質データ [name, base, eff, skill, type, rarity]
// ============================================================
const D=[
  {name:"鋼鉄余音",         base:"敏捷",      eff:"物理ダメージ",  skill:"巧技",  type:"片手剣",         rarity:5},
  {name:"堅城鋳造者",       base:"知性",      eff:"必殺技効率",    skill:"昂揚",  type:"片手剣",         rarity:5},
  {name:"フィンチェイサー3.0",base:"筋力",    eff:"寒冷ダメージ",  skill:"圧制",  type:"片手剣",         rarity:5},
  {name:"十二間",           base:"敏捷",      eff:"攻撃力",        skill:"付術",  type:"片手剣",         rarity:5},
  {name:"O.B.J.軽刃",      base:"敏捷",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:5},
  {name:"抑止",             base:"敏捷",      eff:"物理ダメージ",  skill:"夜幕",  type:"片手剣",         rarity:5},
  {name:"大願",             base:"敏捷",      eff:"攻撃力",        skill:"付術",  type:"片手剣",         rarity:6},
  {name:"不知帰",           base:"意志",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:6},
  {name:"フレイムフォージ", base:"知性",      eff:"攻撃力",        skill:"夜幕",  type:"片手剣",         rarity:6},
  {name:"ダークトーチ",     base:"知性",      eff:"灼熱ダメージ",  skill:"付術",  type:"片手剣",         rarity:6},
  {name:"フーヤオ",         base:"メイン能力", eff:"会心率",        skill:"夜幕",  type:"片手剣",         rarity:6},
  {name:"テルミットカッター",base:"意志",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:6},
  {name:"輝しき名声",       base:"メイン能力", eff:"物理ダメージ",  skill:"残虐",  type:"片手剣",         rarity:6},
  {name:"白夜新星",         base:"メイン能力", eff:"アーツ強度",    skill:"付術",  type:"片手剣",         rarity:6},
  {name:"狼緋",             base:"敏捷",      eff:"会心率",        skill:"切骨",  type:"片手剣",         rarity:6},
  {name:"栄光の記憶",       base:"敏捷",      eff:"会心率",        skill:"夜幕",  type:"片手剣",         rarity:6},
  {name:"探龍",             base:"筋力",      eff:"必殺技効率",    skill:"噴発",  type:"大剣",           rarity:5},
  {name:"千古恒常",         base:"筋力",      eff:"アーツ強度",    skill:"残虐",  type:"大剣",           rarity:5},
  {name:"最期の声",         base:"筋力",      eff:"HPアップ",      skill:"治癒",  type:"大剣",           rarity:5},
  {name:"O.B.J.重責",      base:"筋力",      eff:"HPアップ",      skill:"効率",  type:"大剣",           rarity:5},
  {name:"大雷斑",           base:"筋力",      eff:"HPアップ",      skill:"治癒",  type:"大剣",           rarity:6},
  {name:"クラヴェンガー",   base:"筋力",      eff:"攻撃力",        skill:"噴発",  type:"大剣",           rarity:6},
  {name:"鑑",               base:"メイン能力", eff:"攻撃力",        skill:"圧制",  type:"大剣",           rarity:6},
  {name:"昔日の逸品",       base:"意志",      eff:"HPアップ",      skill:"効率",  type:"大剣",           rarity:6},
  {name:"破砕君主",         base:"筋力",      eff:"会心率",        skill:"破砕",  type:"大剣",           rarity:6},
  {name:"正義嵌合",         base:"筋力",      eff:"必殺技効率",    skill:"残虐",  type:"長柄武器",       rarity:5},
  {name:"O.B.J.鋭矛",      base:"意志",      eff:"物理ダメージ",  skill:"付術",  type:"長柄武器",       rarity:5},
  {name:"求心の槍",         base:"意志",      eff:"電磁ダメージ",  skill:"圧制",  type:"長柄武器",       rarity:5},
  {name:"負山",             base:"敏捷",      eff:"物理ダメージ",  skill:"効率",  type:"長柄武器",       rarity:6},
  {name:"勇猛",             base:"敏捷",      eff:"物理ダメージ",  skill:"巧技",  type:"長柄武器",       rarity:6},
  {name:"J.E.T.",          base:"メイン能力", eff:"攻撃力",        skill:"圧制",  type:"長柄武器",       rarity:6},
  {name:"作品：衆生",       base:"敏捷",      eff:"アーツダメージ",skill:"付術",  type:"拳銃",           rarity:5},
  {name:"O.B.J.迅速",      base:"敏捷",      eff:"必殺技効率",    skill:"噴発",  type:"拳銃",           rarity:5},
  {name:"合理的決別",       base:"筋力",      eff:"灼熱ダメージ",  skill:"追襲",  type:"拳銃",           rarity:5},
  {name:"芸術の独裁者",     base:"知性",      eff:"会心率",        skill:"切骨",  type:"拳銃",           rarity:6},
  {name:"ナビゲーター",     base:"知性",      eff:"寒冷ダメージ",  skill:"付術",  type:"拳銃",           rarity:6},
  {name:"楔",               base:"メイン能力", eff:"会心率",        skill:"付術",  type:"拳銃",           rarity:6},
  {name:"同類共食",         base:"メイン能力", eff:"アーツダメージ",skill:"付術",  type:"拳銃",           rarity:6},
  {name:"落草",             base:"敏捷",      eff:"攻撃力",        skill:"噴発",  type:"拳銃",           rarity:6},
  {name:"望郷",             base:"敏捷",      eff:"寒冷ダメージ",  skill:"圧制",  type:"拳銃",           rarity:6},
  {name:"弔いの詩",         base:"知性",      eff:"攻撃力",        skill:"夜幕",  type:"アーツユニット", rarity:5},
  {name:"術無",             base:"意志",      eff:"必殺技効率",    skill:"昂揚",  type:"アーツユニット", rarity:5},
  {name:"荒野迷走",         base:"知性",      eff:"電磁ダメージ",  skill:"付術",  type:"アーツユニット", rarity:5},
  {name:"布教の自由",       base:"意志",      eff:"回復効率",      skill:"治癒",  type:"アーツユニット", rarity:5},
  {name:"O.B.J.術識",      base:"知性",      eff:"アーツ強度",    skill:"追襲",  type:"アーツユニット", rarity:5},
  {name:"使命必達",         base:"意志",      eff:"必殺技効率",    skill:"追襲",  type:"アーツユニット", rarity:6},
  {name:"蒼星の囁き",       base:"知性",      eff:"回復効率",      skill:"付術",  type:"アーツユニット", rarity:6},
  {name:"作品：蝕跡",       base:"意志",      eff:"自然ダメージ",  skill:"圧制",  type:"アーツユニット", rarity:6},
  {name:"破壊ユニット",     base:"メイン能力", eff:"アーツ強度",    skill:"噴発",  type:"アーツユニット", rarity:6},
  {name:"遺忘",             base:"知性",      eff:"アーツダメージ",skill:"夜幕",  type:"アーツユニット", rarity:6},
  {name:"騎士精神",         base:"意志",      eff:"HPアップ",      skill:"治癒",  type:"アーツユニット", rarity:6},
];

// ============================================================
// アイコン定義
// ============================================================
const BASE_INFO=[
  {name:"筋力",      icon:"images/base_str.png"},
  {name:"敏捷",      icon:"images/base_agi.png"},
  {name:"知性",      icon:"images/base_int.png"},
  {name:"意志",      icon:"images/base_wil.png"},
  {name:"メイン能力",icon:"images/base_star.png"},
];
const BASE_ICON=Object.fromEntries(BASE_INFO.map(b=>[b.name,b.icon]));

const SKILL_ICON={
  "巧技":"images/skill_combative.png",
  "治癒":"images/skill_medicant.png",
  "効率":"images/skill_efficacy.png",
  "付術":"images/skill_infliction.png",
  "噴発":"images/skill_detonate.png",
  "圧制":"images/skill_suppression.png",
  "流回":"images/skill_flow.png",
  "夜幕":"images/skill_twilight.png",
  "追襲":"images/skill_pursuit.png",
  "昂揚":"images/skill_inspiring.png",
  "残虐":"images/skill_brutality.png",
  "切骨":"images/skill_fracture.png",
  "破砕":"images/skill_crusher.png",
};

const EFF_ICON={
  "攻撃力":         "images/eff_atk.png",
  "会心率":         "images/eff_crit.png",
  "必殺技効率":     "images/eff_atkspd.png",
  "アーツダメージ": "images/eff_atk.png",
  "アーツ強度":     "images/arts_strength.png",
  "物理ダメージ":   "images/eff_physical.png",
  "灼熱ダメージ":   "images/eff_heat.png",
  "電磁ダメージ":   "images/eff_electric.png",
  "寒冷ダメージ":   "images/eff_cryo.png",
  "自然ダメージ":   "images/eff_nature.png",
  "HPアップ":       "images/eff_hp.png",
  "回復効率":       "images/recovery_efficiency.png",
};
