// ============================================================
// 基質データ [name, base, eff, skill, type, rarity, en/enFull]
// ============================================================
const D=[
  {name:"鋼鉄余音",         base:"敏捷",      eff:"物理ダメージ",  skill:"巧技",  type:"片手剣",         rarity:5, en:"Sundering_Steel"},
  {name:"堅城鋳造者",       base:"知性",      eff:"必殺技効率",    skill:"昂揚",  type:"片手剣",         rarity:5, en:"Fortmaker"},
  {name:"フィンチェイサー3.0",base:"筋力",    eff:"寒冷ダメージ",  skill:"圧制",  type:"片手剣",         rarity:5, en:"Finchaser_3.0"},
  {name:"十二間",           base:"敏捷",      eff:"攻撃力",        skill:"付術",  type:"片手剣",         rarity:5, en:"Twelve_Questions"},
  {name:"O.B.J.軽刃",      base:"敏捷",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:5, en:"OBJ_Edge_of_Lightness"},
  {name:"抑止",             base:"敏捷",      eff:"物理ダメージ",  skill:"夜幕",  type:"片手剣",         rarity:5, en:"Aspirant"},
  {name:"大願",             base:"敏捷",      eff:"攻撃力",        skill:"付術",  type:"片手剣",         rarity:6, en:"Grand_Vision"},
  {name:"不知帰",           base:"意志",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:6, en:"Never_Rest"},
  {name:"フレイムフォージ", base:"知性",      eff:"攻撃力",        skill:"夜幕",  type:"片手剣",         rarity:6, en:"Forgeborn_Scathe"},
  {name:"ダークトーチ",     base:"知性",      eff:"灼熱ダメージ",  skill:"付術",  type:"片手剣",         rarity:6, en:"Umbral_Torch"},
  {name:"フーヤオ",         base:"メイン能力", eff:"会心率",        skill:"夜幕",  type:"片手剣",         rarity:6, en:"Rapid_Ascent"},
  {name:"テルミットカッター",base:"意志",      eff:"攻撃力",        skill:"流回",  type:"片手剣",         rarity:6, en:"Thermite_Cutter"},
  {name:"輝しき名声",       base:"メイン能力", eff:"物理ダメージ",  skill:"残虐",  type:"片手剣",         rarity:6, en:"Eminent_Repute"},
  {name:"白夜新星",         base:"メイン能力", eff:"アーツ強度",    skill:"付術",  type:"片手剣",         rarity:6, en:"White_Night_Nova"},
  {name:"狼緋",             base:"敏捷",      eff:"会心率",        skill:"切骨",  type:"片手剣",         rarity:6, en:"狼緋"},
  {name:"栄光の記憶",       base:"敏捷",      eff:"会心率",        skill:"夜幕",  type:"片手剣",         rarity:6, enFull:"栄光の記憶"},
  {name:"探龍",             base:"筋力",      eff:"必殺技効率",    skill:"噴発",  type:"大剣",           rarity:5, en:"Seeker_of_Dark_Lung"},
  {name:"千古恒常",         base:"筋力",      eff:"アーツ強度",    skill:"残虐",  type:"大剣",           rarity:5, en:"Ancient_Canal"},
  {name:"最期の声",         base:"筋力",      eff:"HPアップ",      skill:"治癒",  type:"大剣",           rarity:5, en:"Finishing_Call"},
  {name:"O.B.J.重責",      base:"筋力",      eff:"HPアップ",      skill:"効率",  type:"大剣",           rarity:5, en:"OBJ_Heavy_Burden"},
  {name:"大雷斑",           base:"筋力",      eff:"HPアップ",      skill:"治癒",  type:"大剣",           rarity:6, en:"Thunderberge"},
  {name:"クラヴェンガー",   base:"筋力",      eff:"攻撃力",        skill:"噴発",  type:"大剣",           rarity:6, en:"Khravengger"},
  {name:"鑑",               base:"メイン能力", eff:"攻撃力",        skill:"圧制",  type:"大剣",           rarity:6, en:"Exemplar"},
  {name:"昔日の逸品",       base:"意志",      eff:"HPアップ",      skill:"効率",  type:"大剣",           rarity:6, en:"Former_Finery"},
  {name:"破砕君主",         base:"筋力",      eff:"会心率",        skill:"破砕",  type:"大剣",           rarity:6, en:"Sundered_Prince"},
  {name:"正義嵌合",         base:"筋力",      eff:"必殺技効率",    skill:"残虐",  type:"長柄武器",       rarity:5, en:"Chimeric_Justice"},
  {name:"O.B.J.鋭矛",      base:"意志",      eff:"物理ダメージ",  skill:"付術",  type:"長柄武器",       rarity:5, en:"OBJ_Razorhorn"},
  {name:"求心の槍",         base:"意志",      eff:"電磁ダメージ",  skill:"圧制",  type:"長柄武器",       rarity:5, en:"Cohesive_Traction"},
  {name:"負山",             base:"敏捷",      eff:"物理ダメージ",  skill:"効率",  type:"長柄武器",       rarity:6, en:"Mountain_Bearer"},
  {name:"勇猛",             base:"敏捷",      eff:"物理ダメージ",  skill:"巧技",  type:"長柄武器",       rarity:6, en:"Valiant"},
  {name:"J.E.T.",          base:"メイン能力", eff:"攻撃力",        skill:"圧制",  type:"長柄武器",       rarity:6, en:"JET"},
  {name:"作品：衆生",       base:"敏捷",      eff:"アーツダメージ",skill:"付術",  type:"拳銃",           rarity:5, en:"Opus_The_Living"},
  {name:"O.B.J.迅速",      base:"敏捷",      eff:"必殺技効率",    skill:"噴発",  type:"拳銃",           rarity:5, en:"OBJ_Velocitous"},
  {name:"合理的決別",       base:"筋力",      eff:"灼熱ダメージ",  skill:"追襲",  type:"拳銃",           rarity:5, en:"Rational_Farewell"},
  {name:"芸術の独裁者",     base:"知性",      eff:"会心率",        skill:"切骨",  type:"拳銃",           rarity:6, en:"Artzy_Tyrannical"},
  {name:"ナビゲーター",     base:"知性",      eff:"寒冷ダメージ",  skill:"付術",  type:"拳銃",           rarity:6, en:"Navigator"},
  {name:"楔",               base:"メイン能力", eff:"会心率",        skill:"付術",  type:"拳銃",           rarity:6, en:"Wedge"},
  {name:"同類共食",         base:"メイン能力", eff:"アーツダメージ",skill:"付術",  type:"拳銃",           rarity:6, en:"Clannibal"},
  {name:"落草",             base:"敏捷",      eff:"攻撃力",        skill:"噴発",  type:"拳銃",           rarity:6, enFull:"落草"},
  {name:"望郷",             base:"敏捷",      eff:"寒冷ダメージ",  skill:"圧制",  type:"拳銃",           rarity:6, enFull:"栄光の記憶"},
  {name:"弔いの詩",         base:"知性",      eff:"攻撃力",        skill:"夜幕",  type:"アーツユニット", rarity:5, en:"Stanza_of_Memorials"},
  {name:"術無",             base:"意志",      eff:"必殺技効率",    skill:"昂揚",  type:"アーツユニット", rarity:5, en:"Monaihe"},
  {name:"荒野迷走",         base:"知性",      eff:"電磁ダメージ",  skill:"付術",  type:"アーツユニット", rarity:5, en:"Wild_Wanderer"},
  {name:"布教の自由",       base:"意志",      eff:"回復効率",      skill:"治癒",  type:"アーツユニット", rarity:5, en:"Freedom_to_Proselytize"},
  {name:"O.B.J.術識",      base:"知性",      eff:"アーツ強度",    skill:"追襲",  type:"アーツユニット", rarity:5, en:"OBJ_Arts_Identifier"},
  {name:"使命必達",         base:"意志",      eff:"必殺技効率",    skill:"追襲",  type:"アーツユニット", rarity:6, en:"Delivery_Guaranteed"},
  {name:"蒼星の囁き",       base:"知性",      eff:"回復効率",      skill:"付術",  type:"アーツユニット", rarity:6, en:"Dreams_of_the_Starry_Beach"},
  {name:"作品：蝕跡",       base:"意志",      eff:"自然ダメージ",  skill:"圧制",  type:"アーツユニット", rarity:6, en:"Opus_Etch_Figure"},
  {name:"破壊ユニット",     base:"メイン能力", eff:"アーツ強度",    skill:"噴発",  type:"アーツユニット", rarity:6, en:"Detonation_Unit"},
  {name:"遺忘",             base:"知性",      eff:"アーツダメージ",skill:"夜幕",  type:"アーツユニット", rarity:6, en:"Oblivion"},
  {name:"騎士精神",         base:"意志",      eff:"HPアップ",      skill:"治癒",  type:"アーツユニット", rarity:6, en:"Chivalric_Virtues"},
];

// ============================================================
// アイコン定義
// ============================================================
const BASE_INFO=[
  {name:"筋力",      icon:"https://endfield.wiki.gg/images/thumb/STR.png/22px-STR.png?6062bd"},
  {name:"敏捷",      icon:"https://endfield.wiki.gg/images/thumb/AGI.png/22px-AGI.png?505673"},
  {name:"知性",      icon:"https://endfield.wiki.gg/images/thumb/INT.png/22px-INT.png?3b86e1"},
  {name:"意志",      icon:"https://endfield.wiki.gg/images/thumb/WIL.png/22px-WIL.png?966bbb"},
  {name:"メイン能力",icon:"https://endfield.wiki.gg/images/Star.svg?9e1020",iconSize:19},
];
const BASE_ICON=Object.fromEntries(BASE_INFO.map(b=>[b.name,b.icon]));

const SKILL_ICON={
  "巧技":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F436F6D6261746976652E706E67.png",
  "治癒":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F4D65646963616E742E706E67.png",
  "効率":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F45666669636163792E706E67.png",
  "付術":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F496E666C696374696F6E2E706E67.png",
  "噴発":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F4465746F6E6174652E706E67.png",
  "圧制":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F5375707072657373696F6E2E706E67.png",
  "流回":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F466C6F772E706E67.png",
  "夜幕":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F5477696C696768742E706E67.png",
  "追襲":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F507572737569742E706E67.png",
  "昂揚":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F496E73706972696E672E706E67.png",
  "残虐":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F42727574616C6974792E706E67.png",
  "切骨":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F46726163747572652E706E67.png",
  "破砕":"https://arknights-endfield.wikiru.jp/attach2/696D67_466C61776C6573735F457373656E63655F437275736865722E706E67.png",
};

const EFF_ICON={
  "攻撃力":         "https://endfield.wiki.gg/images/thumb/ATK.png/22px-ATK.png?cc7064",
  "会心率":         "https://endfield.wiki.gg/images/thumb/Critical_Rate_Icon.png/22px-Critical_Rate_Icon.png?3a887f",
  "必殺技効率":     "https://endfield.wiki.gg/images/thumb/Attack_Speed.png/22px-Attack_Speed.png?354454",
  "アーツダメージ": "https://endfield.wiki.gg/images/thumb/ATK.png/22px-ATK.png?cc7064",
  "アーツ強度":     "images/arts_strength_icon.png",
  "物理ダメージ":   "https://endfield.wiki.gg/images/thumb/Physical.png/22px-Physical.png?c4b390",
  "灼熱ダメージ":   "https://endfield.wiki.gg/images/thumb/Heat.png/22px-Heat.png?e9026c",
  "電磁ダメージ":   "https://endfield.wiki.gg/images/thumb/Electric.png/22px-Electric.png?cf9565",
  "寒冷ダメージ":   "https://endfield.wiki.gg/images/thumb/Cryo.png/22px-Cryo.png?c1cf2b",
  "自然ダメージ":   "https://endfield.wiki.gg/images/thumb/Nature.png/22px-Nature.png?baac89",
  "HPアップ":       "https://endfield.wiki.gg/images/thumb/MaxHP.png/22px-MaxHP.png?80bd47",
  "回復効率":       "images/recovery_efficiency_icon.png",
};
